# Resolve react_native_pods.rb with node to allow for hoisting
require_relative '../node_modules/react-native-permissions/scripts/setup.rb'
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

config = use_native_modules!

target 'Melon' do
  pod 'ffmpeg-kit-react-native', :path => '../node_modules/ffmpeg-kit-react-native' # 或者你的 fork 路径
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  setup_permissions([
    'Microphone', # 麦克风
    # 也可以加其他，比如 'CAMERA', 'LOCATION', 'PHOTO_LIBRARY'
  ])
end

 target 'MelonApp' do
   pod 'ffmpeg-kit-react-native', :path => '../node_modules/ffmpeg-kit-react-native' # 或者你的 fork 路径
   pod 'Ads-CN-Beta','7.1.0.6', :subspecs => ['BUAdSDK', 'BUAdTestMeasurement']
   use_react_native!(
     :path => config[:reactNativePath],
     # An absolute path to your application root.
     :app_path => "#{Pod::Config.instance.installation_root}/.."
   )

   setup_permissions([
     'Microphone', # 麦克风
     # 也可以加其他，比如 'CAMERA', 'LOCATION', 'PHOTO_LIBRARY'
   ])
 end

 target 'MelonsApp' do
   pod 'ffmpeg-kit-react-native', :path => '../node_modules/ffmpeg-kit-react-native' # 或者你的 fork 路径
   pod 'Ads-CN-Beta','7.1.0.6', :subspecs => ['BUAdSDK', 'BUAdTestMeasurement']
   use_react_native!(
     :path => config[:reactNativePath],
     # An absolute path to your application root.
     :app_path => "#{Pod::Config.instance.installation_root}/.."
   )

   setup_permissions([
     'Microphone', # 麦克风
     # 也可以加其他，比如 'CAMERA', 'LOCATION', 'PHOTO_LIBRARY'
   ])
 end

target 'MomorApp' do
  pod 'ffmpeg-kit-react-native', :path => '../node_modules/ffmpeg-kit-react-native' # 或者你的 fork 路径
  pod 'Ads-CN-Beta','7.1.0.6', :subspecs => ['BUAdSDK', 'BUAdTestMeasurement']
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  setup_permissions([
    'Microphone', # 麦克风
    # 也可以加其他，比如 'CAMERA', 'LOCATION', 'PHOTO_LIBRARY'
  ])
end

target 'MomorsApp' do
  pod 'ffmpeg-kit-react-native', :path => '../node_modules/ffmpeg-kit-react-native' # 或者你的 fork 路径
  pod 'Ads-CN-Beta','7.1.0.6', :subspecs => ['BUAdSDK', 'BUAdTestMeasurement']
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  setup_permissions([
    'Microphone', # 麦克风
    # 也可以加其他，比如 'CAMERA', 'LOCATION', 'PHOTO_LIBRARY'
  ])
end

post_install do |installer|
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )
end
