const HTML = `
    <!DOCTYPE html>\n
    <html>
        <head>
            <meta http-equiv="content-type" content="text/html; charset=utf-8">
            <meta name="viewport" content="width=320, user-scalable=no">
            <style type="text/css">
                body {
                    background: #262626;
                    color: #fff;
                    font-size: 16px;
                    line-height: 24px
                }
                .blueText {
                    color: #336df4;
                }
                ol,ul {
                    padding-left: 16px;
                }
                li:not(:first-child) {
                    margin-top: 10px;
                }
            </style>
        </head>
        <body>
            <h2 class="code-line" data-line-start=0 data-line-end=1 ><a id="Melon_Terms_of_Service_0"></a>Melon Terms of Service</h2>
            <p class="has-line-data" data-line-start="1" data-line-end="3"><strong>Effective Date</strong>: September 6, 2025<br>
            <strong>Last Updated</strong>: September 6, 2025</p>
            <h3 class="code-line" data-line-start=4 data-line-end=5 ><a id="1_Acceptance_of_These_Terms_of_Service_4"></a>1. Acceptance of These Terms of Service</h3>
            <h4 class="code-line" data-line-start=5 data-line-end=6 ><a id="11_Parties_and_Service_Description_5"></a>1.1 Parties and Service Description</h4>
            <p class="has-line-data" data-line-start="6" data-line-end="7">Welcome to Melon. These Terms of Service (the “Terms”) constitute a legally binding agreement between you (“User,” “you,” or “your”) and Sinobiz llc (“Melon,” “we,” “us,” or “our”), a service operated by Sinobiz llc, with a registered address at 30N GOULD ST STE R SHERIDAN, WY 82801.</p>
            <p class="has-line-data" data-line-start="8" data-line-end="9">These Terms govern your registration for, access to, and use of the Melon mobile application, our official website located at <span class="blueText">www.sinobiz.biz</span>, and all related content, software, features, and technologies (collectively, the “Service”).</p>
            <p class="has-line-data" data-line-start="10" data-line-end="11">The Service is designed to provide innovative cross-language communication and music creation experiences through advanced artificial intelligence, including AI Translation Services (text, voice, document, and image translation) and AI Music Generation Services (original music generation, AI song covers, and voice model cloning).</p>
            <p class="has-line-data" data-line-start="12" data-line-end="13">By checking the box to indicate your agreement during registration, or by accessing or using the Service in any manner, you acknowledge that you have read, understood, and agree to be bound by the entirety of these Terms and our accompanying Melon Privacy Policy, which is incorporated herein by reference.</p>
            <p class="has-line-data" data-line-start="14" data-line-end="15">If you do not agree to any part of these Terms, you must immediately cease all access to and use of the Service.</p>
            <h4 class="code-line" data-line-start=15 data-line-end=16 ><a id="12_Changes_to_Terms_15"></a>1.2 Changes to Terms</h4>
            <p class="has-line-data" data-line-start="16" data-line-end="17">We reserve the right, at our sole discretion, to modify or replace these Terms at any time to reflect changes in the law, our business, or the features of the Service. For the purpose of this section, “material changes” include but are not limited to: (a) adjustments to fee structures or refund policies; (b) modifications to intellectual property ownership of AI-generated content; © changes to dispute resolution methods (e.g., arbitration rules); (d) restrictions on core service functions; (e) updates to data usage rights related to user Input. If we make changes that are material, we will provide you with reasonable notice of such changes (at least 7 calendar days in advance for non-urgent changes) by posting a notice within the Service user interface, sending a pop-up notification, or sending an email to the address associated with your account. The “Last Updated” date at the top of this page will indicate when the latest modifications were made. Your continued use of the Service after any such changes become effective constitutes your binding acceptance of the new Terms. If you do not agree to the revised Terms, you must stop using the Service.</p>
            <h4 class="code-line" data-line-start=17 data-line-end=18 ><a id="13_ARBITRATION_NOTICE_AND_CLASS_ACTION_WAIVER_17"></a>1.3 ARBITRATION NOTICE AND CLASS ACTION WAIVER</h4>
            <p class="has-line-data" data-line-start="18" data-line-end="19">PLEASE READ THIS SECTION CAREFULLY. THESE TERMS CONTAIN A MANDATORY INDIVIDUAL ARBITRATION PROVISION AND A CLASS ACTION/JURY TRIAL WAIVER.WITH LIMITED EXCEPTIONS, THIS REQUIRES YOU TO SUBMIT ANY DISPUTES YOU HAVE WITH US TO BINDING AND FINAL ARBITRATION ON AN INDIVIDUAL BASIS.THIS MEANS YOU WAIVE YOUR RIGHT TO SEEK RELIEF IN A COURT OF LAW (INCLUDING THE RIGHT TO A JURY TRIAL) AND TO PARTICIPATE IN ANY CLASS ACTION, REPRESENTATIVE ACTION, OR SIMILAR PROCEEDING AGAINST US.A detailed explanation of this provision is located in Section 9 of these Terms.</p>
            <h3 class="code-line" data-line-start=20 data-line-end=21 ><a id="2_Your_Melon_Account_20"></a>2. Your Melon Account</h3>
            <h4 class="code-line" data-line-start=21 data-line-end=22 ><a id="21_Eligibility_21"></a>2.1 Eligibility</h4>
            <p class="has-line-data" data-line-start="22" data-line-end="23">The Service is intended for a general audience and is not directed to children.To create an account and use the Service, you must be at least 13 years of age.If you are between the ages of 13 and 18 (or the age of legal majority in your jurisdiction, e.g., 16 in the EEA), you may only use the Service under the supervision of a parent or legal guardian who: (a) explicitly consents to these Terms on your behalf by providing their valid email address or phone number for verification (we will send a verification link/code to the provided contact, and the guardian must complete verification within 48 hours); (b) reviews your use of the Service (including Input content and AI-generated Output) at least monthly via the “Family Management Center” (a dedicated portal for guardians to register and access the minor’s usage records, including Input history and Output files); © agrees to be liable for any violations of these Terms caused by your use. By using the Service, you represent and warrant that you meet these eligibility requirements, and that your parent or legal guardian has completed the consent verification process as required.</p>
            <h4 class="code-line" data-line-start=23 data-line-end=24 ><a id="22_Registration_and_Account_Information_23"></a>2.2 Registration and Account Information</h4>
            <p class="has-line-data" data-line-start="24" data-line-end="25">You may be required to register for an account to access certain features of the Service, using either a mobile phone number or an email address. You agree to provide and maintain true, accurate, current, and complete information about yourself as prompted by the registration form. You may not create more than one account for the purpose of abusing any free tier, promotional offers, or other features of the Service. If we believe, in our sole discretion, that you are not using any free tier in good faith, we reserve the right to suspend or terminate your access to the Service.</p>
            <h4 class="code-line" data-line-start=25 data-line-end=26 ><a id="23_Account_Security_25"></a>2.3 Account Security</h4>
            <p class="has-line-data" data-line-start="26" data-line-end="27">You are solely responsible for maintaining the confidentiality of your account password and for all activities that occur under your account, including but not limited to information publishing, feature usage, and Credit purchases or consumption. You agree to immediately notify Melon of any unauthorized use of your password or account or any other breach of security. Melon will not be liable for any loss or damage arising from your failure to comply with this section.</p>
            <h4 class="code-line" data-line-start=27 data-line-end=28 ><a id="24_Account_Termination_and_Deletion_27"></a>2.4 Account Termination and Deletion</h4>
            <p class="has-line-data" data-line-start="28" data-line-end="29">You may request to delete your account at any time through the “Account and Security” section within the application. Upon confirmation, your account access will be disabled immediately, and all associated data (including Input content, usage logs, and account information) will be permanently and irretrievably erased within 30 calendar days. We will send a confirmation email to your registered address once the deletion is completed. All remaining virtual “Credits” will be invalidated upon account deletion request submission. We will cease providing the Service to you upon account deletion.</p>
            <p class="has-line-data" data-line-start="30" data-line-end="31">We reserve the right to suspend or terminate your account and your access to the Service for any reason, including but not limited to: (a) a breach of these Terms; (b) engaging in fraudulent, abusive, or illegal activity; or © prolonged periods of inactivity (defined as no login or service usage for 12 consecutive months). For termination due to prolonged inactivity: (i) we will send you a notice via your registered email/phone number at least 30 calendar days before termination; (ii) the notice will include information on how to reactivate your account (e.g., logging in within 30 days) and the consequences of non-reactivation (e.g., permanent deletion of account data and remaining Credits). We may terminate your account without prior notice only if: (x) your account is involved in illegal activities (e.g., using voice cloning for fraud); (y) we receive a valid legal order requiring immediate termination.</p>
            <h3 class="code-line" data-line-start=32 data-line-end=33 ><a id="3_Virtual_Credits_Fees_and_Payments_32"></a>3. Virtual Credits, Fees, and Payments</h3>
            <h4 class="code-line" data-line-start=33 data-line-end=34 ><a id="31_Virtual_Credits_33"></a>3.1 Virtual “Credits”</h4>
            <p class="has-line-data" data-line-start="34" data-line-end="35">The Service may offer certain premium features that can be accessed by using a virtual item referred to as “Credits”. These Credits are not currency or property of any kind; they are a limited, non-transferable, non-sublicensable, revocable license to use designated features of the Service. Credits have no monetary value, cannot be redeemed for cash or used for any purpose outside of the Service, and expire 12 months from the date of purchase or acquisition (free/promotional Credits expire 3 months from acquisition). We will send you a reminder via in-app message/email 30 days before your Credits expire; if the in-app message/email fails to reach you (e.g., email bounce-back, unread in-app notification), we will send an additional SMS reminder to your registered phone number (if provided) 15 days before expiration, and display a mandatory pop-up reminder upon your next login within 7 days of expiration. If your account is suspended or terminated due to a misunderstanding or our error (e.g., false detection of abuse), you may request to: (i) reactivate your account (if suspended) to use remaining Credits; (ii) transfer remaining valid Credits to another Melon account (with proof of ownership of both accounts, such as a government-issued ID matching the account registration information) within 15 days of account reactivation. If your account is terminated for breach of these Terms, all remaining Credits will be forfeited without compensation.</p>
            <p class="has-line-data" data-line-start="36" data-line-end="37">You are strictly prohibited from selling, trading, gifting, or otherwise transferring credits to other users. Any attempt to do so is a violation of these Terms and may result in the immediate termination of your account and the forfeiture of all remaining Credits.</p>
            <h4 class="code-line" data-line-start=37 data-line-end=38 ><a id="32_Payment_and_Billing_37"></a>3.2 Payment and Billing</h4>
            <p class="has-line-data" data-line-start="38" data-line-end="39">To the extent any portion of the Service is made available for a fee, you will be required to provide payment information. All financial transactions are processed through third-party payment processors, such as Apple’s or Google’s in-app payment systems or other providers like Stripe. We do not collect or store your full payment card details. You represent and warrant that you are authorized to use the payment instrument you provide and that all information you submit is true and accurate. You agree to pay all fees and applicable taxes incurred by you or anyone using an account registered to you.</p>
            <h4 class="code-line" data-line-start=39 data-line-end=40 ><a id="33_NO_REFUNDS_39"></a>3.3 NO REFUNDS</h4>
            <p class="has-line-data" data-line-start="40" data-line-end="41">You understand and agree that all payments made for Credits or other aspects of the Service are final and non-refundable, unless otherwise required by applicable law. Specific statutory refund rights by jurisdiction include but are not limited to: (a) For users in the EEA: Right to withdraw within 14 calendar days of payment if no Credits have been used (per EU Consumer Rights Directive); (b) For users in China: Right to a full refund if the Service is unavailable for more than 7 consecutive days due to our technical fault; © For users in California (U.S.): Right to a pro-rata refund for unused Credits if we terminate your account without valid cause. If you reside in a jurisdiction that provides a statutory right of withdrawal or refund, your rights will be governed by that jurisdiction’s laws.</p>
            <p class="has-line-data" data-line-start="42" data-line-end="43">In addition to statutory refund rights, if you purchase Credits but do not use them within 30 days, and you are unable to continue using the Service due to our direct fault (e.g., permanent discontinuation of core features you purchased Credits for, account suspension due to our system error), you may submit a refund request via the “Help Center” in the application, providing proof of purchase and a description of the issue. We will review your request within 15 business days and notify you of the decision; if approved, the refund will be processed within 7 business days to your original payment method.</p>
            <p class="has-line-data" data-line-start="44" data-line-end="45">In the event of a system malfunction or billing error, we reserve the right to correct such an error. If the error results in you receiving fewer Credits than you were entitled to, we will credit your account for the difference within 3 business days. If the error results in you receiving more Credits than you were entitled to, we will notify you in writing and debit the excess Credits from your account within 5 business days (or provide a repayment plan if the excess is significant, allowing you to use the excess Credits within a 30-day period or pay the equivalent monetary value of the excess).</p>
            <h3 class="code-line" data-line-start=46 data-line-end=47 ><a id="4_Intellectual_Property_Rights_46"></a>4. Intellectual Property Rights</h3>
            <h4 class="code-line" data-line-start=47 data-line-end=48 ><a id="41_Our_Rights_in_the_Service_47"></a>4.1 Our Rights in the Service</h4>
            <p class="has-line-data" data-line-start="48" data-line-end="49">You acknowledge and agree that the Service and all of its underlying technology, software, user interfaces, branding, trademarks, and content (excluding your Content, as defined below) are the exclusive property of Sinobiz llc and its licensors.These are protected by copyright, trademark, and other intellectual property laws.Except as expressly authorized by these Terms, you agree not to copy, modify, rent, sell, distribute, or create derivative works based on the Service, in whole or in part.</p>
            <h4 class="code-line" data-line-start=49 data-line-end=50 ><a id="42_Your_Content_Inputs_and_the_License_You_Grant_Us_49"></a>4.2 Your Content: Inputs and the License You Grant Us</h4>
            <p class="has-line-data" data-line-start="50" data-line-end="51">The Service allows you to provide various forms of data, including text for translation, lyrics for music generation, audio files for voice cloning or AI covers, images, and documents (collectively, your “Input”). You retain any ownership rights you have in your Input.</p>
            <p class="has-line-data" data-line-start="52" data-line-end="53">However, to operate and improve the service, we need certain permissions from you. You represent and warrant that you own your input or have obtained all necessary rights, licenses, consents, and permissions to submit it to the Service and to grant us the license described below. You further warrant that your Input, and our use of it as permitted by these Terms, will not infringe, misappropriate, or violate any third party’s rights, including intellectual property rights, privacy rights, or rights of publicity.</p>
            <p class="has-line-data" data-line-start="54" data-line-end="55">By submitting Input to the Service, you grant Melon a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to use, host, store, reproduce, modify, create derivative works of, distribute, and otherwise process your Input for the limited purposes of operating, providing, securing, and improving the Service. This includes using your Input to train and enhance our artificial intelligence models that power the Service. For more information on how we use your data and how you can control its use for model improvement, please see our Privacy Policy.</p>
            <h4 class="code-line" data-line-start=55 data-line-end=56 ><a id="43_AIGenerated_Content_Output_55"></a>4.3 AI-Generated Content (“Output”)</h4>
            <p class="has-line-data" data-line-start="56" data-line-end="57">The Service generates content such as translated text, musical compositions, and AI-generated song covers based on your Input (collectively, “Output”). The intellectual property rights in this Output are determined by the type of Credits used to generate it, as detailed below.</p>
            <h4 class="code-line" data-line-start=57 data-line-end=58 ><a id="431_Output_Generated_with_Paid_Credits_57"></a>4.3.1 Output Generated with Paid Credits</h4>
            <p class="has-line-data" data-line-start="58" data-line-end="59">Subject to your full compliance with these Terms, for any Output you generate through the consumption of Credits that you have purchased with real money, we hereby assign to you all of our right, title, and interest, if any, in and to that specific Output. You are free to use such Output for any lawful purpose, including for commercial use, at your own risk.</p>
            <h4 class="code-line" data-line-start=59 data-line-end=60 ><a id="432_Output_Generated_with_Free_or_Promotional_Credits_59"></a>4.3.2 Output Generated with Free or Promotional Credits</h4>
            <p class="has-line-data" data-line-start="60" data-line-end="61">For any Output you generate through the consumption of Credits obtained for free (including but not limited to registration bonuses, referral rewards, or rewards for watching advertisements), we grant you a limited, personal, non-exclusive, non-transferable, and non-sublicensable license to use, reproduce, and display the Output solely for your own personal, non-commercial purposes. If you share or display such Output publicly, you must provide attribution in the following manner: (a) For text-based Output (e.g., translated articles): Place the attribution “Generated with Melon” at the end of the text, in a font size no smaller than 80% of the main text; (b) For audio/video Output (e.g., AI covers, music videos): Include the attribution “Generated with Melon” in the opening 10 seconds or closing 5 seconds of the file, with clear visibility/audibility (e.g., text overlay for video, voiceover for audio); © For social media sharing (e.g., Instagram Reels, TikTok): If character/time limits prevent full attribution, use the simplified tag “via Melon” and link to the Melon official website (<span class="blueText">www.sinobiz.biz</span>) in the post description.</p>
            <h4 class="code-line" data-line-start=61 data-line-end=62 ><a id="433_IMPORTANT_DISCLAIMER_ON_AI_OUTPUT_61"></a>4.3.3 IMPORTANT DISCLAIMER ON AI OUTPUT</h4>
            <p class="has-line-data" data-line-start="62" data-line-end="63">THE ASSIGNMENT OF RIGHTS IN SECTION 4.3.1 APPLIES ONLY TO THE RIGHTS, IF ANY, THAT MELON HOLDS IN THE OUTPUT. DUE TO THE NATURE OF ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING, OUTPUT MAY NOT BE UNIQUE, AND THE SERVICE MAY GENERATE IDENTICAL OR SUBSTANTIALLY SIMILAR OUTPUT FOR OTHER USERS FROM DIFFERENT INPUT. Accordingly, we make no representations or warranties of any kind regarding the copyrightability, uniqueness, originality, or non-infringement of any Output.</p>
            <p class="has-line-data" data-line-start="64" data-line-end="65">If you use Output for commercial purposes and incur losses due to Output non-uniqueness (e.g., third-party claims of copyright infringement, loss of business opportunities), we will not be liable for direct or indirect damages, but will provide reasonable technical assistance (e.g., providing a timestamped record of your Output generation to prove priority) upon your request. Before using any Output for commercial purposes, you are required to: (a) conduct a copyright search (e.g., via official copyright databases such as the U.S. Copyright Office’s Public Catalog, EUIPO’s TMview) to confirm no third-party rights are infringed; (b) review the Output for compliance with local laws (e.g., advertising regulations for commercial use). A pop-up reminder of this requirement will appear each time you generate Output using paid Credits. You are solely responsible for determining whether any Output is suitable for your intended use and does not infringe on the rights of any third party.</p>
            <h3 class="code-line" data-line-start=66 data-line-end=67 ><a id="5_Special_Terms_for_Voice_Cloning_and_AI_Covers_66"></a>5. Special Terms for Voice Cloning and AI Covers</h3>
            <p class="has-line-data" data-line-start="67" data-line-end="68">The voice cloning and AI cover features of the Service present unique legal risks related to intellectual property and the rights of individuals. Your use of these features is subject to the following strict conditions.</p>
            <h4 class="code-line" data-line-start=68 data-line-end=69 ><a id="51_Strict_Prohibition_68"></a>5.1 Strict Prohibition</h4>
            <p class="has-line-data" data-line-start="69" data-line-end="70">YOU ARE STRICTLY PROHIBITED FROM UPLOADING ANY AUDIO, CREATING A VOICE MODEL, OR GENERATING AN AI COVER USING THE VOICE OF ANY THIRD PARTY (INCLUDING, BUT NOT LIMITED TO, PUBLIC FIGURES, RECORDING ARTISTS, ACTORS, FRIENDS, OR FAMILY MEMBERS) UNLESS YOU: (a) obtain that individual’s prior, explicit, and verifiable written consent (signed physical document or encrypted digital signature, e.g., via DocuSign), which must include the individual’s full name, contact information, a clear statement of consent to voice cloning/AI cover use, and the effective period of consent (no longer than 12 months); (b) submit the consent document to our compliance team via email (<span class="blueText">zhangjian@sinobiz.biz</span>) for verification; © receive written confirmation from us that the consent is valid (verification will be completed within 3 business days). We reserve the right to reject any consent document that is incomplete, ambiguous, or appears forged.</p>
            <h4 class="code-line" data-line-start=70 data-line-end=71 ><a id="52_Your_Warranty_and_Responsibility_70"></a>5.2 Your Warranty and Responsibility</h4>
            <p class="has-line-data" data-line-start="71" data-line-end="72">By using these features, you expressly represent and warrant that you have secured all necessary rights, licenses, and permissions for any voice you clone or use. You are solely and exclusively responsible and liable for all voice models you create and all Output generated using them.</p>
            <h4 class="code-line" data-line-start=72 data-line-end=73 ><a id="53_Our_Right_to_Monitor_and_Remove_72"></a>5.3 Our Right to Monitor and Remove</h4>
            <p class="has-line-data" data-line-start="73" data-line-end="74">We reserve the right, but do not have the obligation, to review, screen, or remove any voice models or Output that we believe, in our sole discretion, may violate these Terms, infringe on the rights of a third party, or otherwise be objectionable. We may also suspend or terminate the accounts of users who engage in such activities.</p>
            <h4 class="code-line" data-line-start=74 data-line-end=75 ><a id="54_Your_Obligation_to_Indemnify_Us_74"></a>5.4 Your Obligation to Indemnify Us</h4>
            <p class="has-line-data" data-line-start="75" data-line-end="76">In addition to the general indemnification clause in Section 8, you specifically agree to defend, indemnify, and hold harmless Sinobiz llc and its affiliates, officers, directors, employees, and agents from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys’ fees) arising out of or related to your use of the voice cloning or AI cover features in violation of these Terms or any applicable law, including claims for copyright infringement, violation of the right of publicity, defamation, or unauthorized use of a third party’s voice identity. This indemnification obligation applies even if the claim arises from an error in our verification of third-party consent (e.g., a forged consent document that we reasonably approved), provided that you failed to disclose material information about the consent’s validity.</p>
            <h3 class="code-line" data-line-start=77 data-line-end=78 ><a id="6_User_Conduct_and_Restrictions_77"></a>6. User Conduct and Restrictions</h3>
            <p class="has-line-data" data-line-start="78" data-line-end="79">You agree not to use the Service to create, upload, or distribute any Input or Output that:</p>
            <ul>
            <li class="has-line-data" data-line-start="79" data-line-end="80">Is unlawful, defamatory, obscene, abusive, invasive of privacy (including but not limited to non-consensual sharing of personal information), or otherwise objectionable (e.g., content that promotes hate speech, violence, discrimination based on race, gender, religion, or disability);</li>
            <li class="has-line-data" data-line-start="80" data-line-end="81">Infringes upon the intellectual property or other proprietary rights of any party (e.g., unlicensed use of copyrighted music, trademarks, or patented technology in Input);</li>
            <li class="has-line-data" data-line-start="81" data-line-end="82">Contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware (e.g., malware, ransomware, or phishing scripts);</li>
            <li class="has-line-data" data-line-start="82" data-line-end="84">Constitutes unsolicited or unauthorized advertising or promotional materials (e.g., spam messages, pyramid schemes, or affiliate marketing links shared without prior written approval from Melon).<br>
            Furthermore, you agree not to:</li>
            <li class="has-line-data" data-line-start="84" data-line-end="85">Reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code of the Service, except to the extent permitted by applicable law (e.g., fair use provisions for software interoperability);</li>
            <li class="has-line-data" data-line-start="85" data-line-end="86">Use any robot, spider, scraper, or other automated means to access the Service for any purpose without our express written permission (e.g., automated scripts to generate unlimited free Output or scrape user-generated content);</li>
            <li class="has-line-data" data-line-start="86" data-line-end="87">Interfere with or disrupt the Service or servers or networks connected to the Service (e.g., DDoS attacks, overloading servers by sending excessive requests, or bypassing rate limits);</li>
            <li class="has-line-data" data-line-start="87" data-line-end="88">Use the Service or any Output to create, train, or improve (directly or indirectly) any other artificial intelligence, machine learning models, or any service that competes with Melon (e.g., using Melon’s translated text to train a rival translation AI, or using AI-generated music to develop a competing music generation tool);</li>
            <li class="has-line-data" data-line-start="88" data-line-end="90">Circumvent any security measures or access controls we implement (e.g., using a VPN to bypass regional restrictions on the Service, or modifying the Service’s code to unlock premium features without purchasing Credits).</li>
            </ul>
            <p class="has-line-data" data-line-start="90" data-line-end="91">You agree to report any violations of these Terms by other users via the “Report” button in the Service (located next to user-generated content) or by emailing our trust and safety team at <span class="blueText">zhangjian@sinobiz.biz</span>. When reporting, you must provide: (a) the username of the violating user; (b) screenshots or links to the violating content (with timestamps if applicable); © a detailed description of how the content violates these Terms (e.g., “uses a celebrity’s voice for AI covers without consent”). We will review all reports within 48 hours and notify you of the review result (e.g., content removed, account suspended, or no violation found) via in-app message. If we determine a violation occurred, we will take action within 24 hours of the review conclusion, which may include removing the content, issuing a warning to the violating user, or suspending/terminating their account.</p>
            <h3 class="code-line" data-line-start=92 data-line-end=93 ><a id="7_Disclaimers_and_Limitation_of_Liability_92"></a>7. Disclaimers and Limitation of Liability</h3>
            <h4 class="code-line" data-line-start=93 data-line-end=94 ><a id="71_Disclaimer_of_Warranties_93"></a>7.1 Disclaimer of Warranties</h4>
            <p class="has-line-data" data-line-start="94" data-line-end="95">YOUR USE OF THE SERVICE AND ANY OUTPUT IS AT YOUR SOLE RISK. THE SERVICE AND ALL OUTPUT ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. SINOBIZ LLC AND ITS AFFILIATES EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.</p>
            <p class="has-line-data" data-line-start="96" data-line-end="97">WE DO NOT WARRANT THAT: (A) THE SERVICE WILL MEET YOUR REQUIREMENTS (E.G., AI TRANSLATION ACCURACY FOR HIGHLY SPECIALIZED TECHNICAL TEXT); (B) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE (E.G., TEMPORARY OUTAGES DUE TO SERVER MAINTENANCE); OR © THE RESULTS OR OUTPUT OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE, RELIABLE, OR LAWFUL (E.G., TRANSLATIONS CONTAINING CULTURALLY INSENSITIVE LANGUAGE, OR AI MUSIC THAT INADVERTENTLY RESEMBLES COPYRIGHTED WORKS).</p>
            <p class="has-line-data" data-line-start="98" data-line-end="99">YOU ACKNOWLEDGE THAT THE SERVICE USES EXPERIMENTAL TECHNOLOGY AND MAY SOMETIMES PROVIDE INACCURATE, OFFENSIVE, OR MISLEADING CONTENT THAT DOES NOT REPRESENT THE VIEWS OF SINOBIZ LLC. We reserve the right to disable access to any Output that we determine is harmful or non-compliant, even after it has been generated for you.</p>
            <h4 class="code-line" data-line-start=99 data-line-end=100 ><a id="72_Limitation_of_Liability_99"></a>7.2 Limitation of Liability</h4>
            <p class="has-line-data" data-line-start="100" data-line-end="101">YOU EXPRESSLY UNDERSTAND AND AGREE THAT SINOBIZ LLC AND ITS AFFILIATES WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY DAMAGES, OR DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES (EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE, RESULTING FROM: (A) YOUR USE OF OR INABILITY TO USE THE SERVICE; (B) ANY CHANGES TO THE SERVICE OR DISCONTINUATION OF ANY FEATURES; © UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (D) STATEMENTS OR CONDUCT OF ANY THIRD PARTY USING THE SERVICE; (E) ANY OUTPUT GENERATED BY THE SERVICE, INCLUDING BUT NOT LIMITED TO DAMAGES ARISING FROM INFRINGEMENT, DEFAMATION, OR INACCURACY; OR (F) ANY OTHER MATTER RELATING TO THE SERVICE.</p>
            <p class="has-line-data" data-line-start="102" data-line-end="103">IN NO EVENT WILL THE TOTAL LIABILITY OF SINOBIZ LLC AND ITS AFFILIATES TO YOU FOR ALL DAMAGES, LOSSES, OR CAUSES OF ACTION EXCEED THE AMOUNT YOU HAVE PAID US IN THE LAST SIX (6) MONTHS, OR, IF GREATER, ONE HUNDRED U.S. DOLLARS ($100). This limitation of liability does not apply to: (a) our intentional misconduct (e.g., deliberate disclosure of your personal information without authorization, or intentional manipulation of Output to cause harm); (b) gross negligence (e.g., failure to implement basic data security measures leading to a data breach, or reckless disregard for third-party intellectual property rights in Output); © violations of applicable data protection laws (e.g., GDPR, CCPA/CPRA, or China’s PIPL); or (d) damages arising from death or personal injury caused by our negligence. For claims covered by this exception, liability will be calculated based on actual damages incurred (e.g., financial losses from identity theft, medical expenses from harm caused by misleading Output, or legal fees for defending third-party infringement claims).</p>
            <h3 class="code-line" data-line-start=104 data-line-end=105 ><a id="8_Indemnification_104"></a>8. Indemnification</h3>
            <p class="has-line-data" data-line-start="105" data-line-end="106">To the fullest extent permitted by law, you agree to defend, indemnify, and hold harmless Sinobiz llc, its affiliates, and their respective officers, directors, employees, agents, licensors, and suppliers from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to reasonable attorneys’ fees, court costs, and investigation expenses) arising from: (a) your use of and access to the Service (including any use by a minor under your supervision); (b) your violation of any term of these Terms (e.g., unauthorized transfer of Credits, use of voice cloning without third-party consent); © your violation of any third-party right, including without limitation any copyright, trademark, patent, trade secret, privacy right, right of publicity, or contractual right; (d) any claim that your Input or Output caused damage to a third party (e.g., defamatory text, infringing music); or (e) your breach of any representation or warranty in these Terms (e.g., misrepresentation of your eligibility to use the Service).</p>
            <p class="has-line-data" data-line-start="107" data-line-end="108">We reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of such claims. You may not settle any such claim without our prior written consent. If we determine that your actions have exposed us to potential liability, we may, in our sole discretion, suspend or terminate your account until the indemnification obligation is fulfilled.</p>
            <h3 class="code-line" data-line-start=109 data-line-end=110 ><a id="9_Dispute_Resolution_by_Binding_Arbitration_and_Class_Action_Waiver_109"></a>9. Dispute Resolution by Binding Arbitration and Class Action Waiver</h3>
            <h4 class="code-line" data-line-start=110 data-line-end=111 ><a id="91_Agreement_to_Arbitrate_110"></a>9.1 Agreement to Arbitrate</h4>
            <p class="has-line-data" data-line-start="111" data-line-end="112">This section is referred to as the “Arbitration Agreement.” You and Sinobiz llc agree that any and all disputes or claims that have arisen or may arise between you and us, whether arising out of or relating to these Terms, the Service, the Privacy Policy, or any aspect of the relationship between us (including but not limited to claims based on contract, tort, statute, fraud, misrepresentation, or other legal theories), shall be resolved exclusively through final and binding arbitration, rather than in court. The Federal Arbitration Act (FAA) governs the interpretation and enforcement of this Arbitration Agreement, and you and we agree to be bound by the FAA’s provisions. This Arbitration Agreement survives termination of these Terms and your use of the Service.</p>
            <h4 class="code-line" data-line-start=112 data-line-end=113 ><a id="92_Governing_Body_and_Rules_112"></a>9.2 Governing Body and Rules</h4>
            <ul>
            <li class="has-line-data" data-line-start="113" data-line-end="114">If you are an individual using the Service for personal, non-commercial purposes: The arbitration will be conducted by the American Arbitration Association (“AAA”) under its Consumer Arbitration Rules (available at <span class="blueText">www.adr.org/consumer-rules</span>). If you are a resident outside the United States, you may request to use the AAA’s International Centre for Dispute Resolution (“ICDR”) International Consumer Dispute Resolution Procedures (available at <span class="blueText">www.icdr.org</span>) if it is more convenient for you.</li>
            <li class="has-line-data" data-line-start="114" data-line-end="116">If you are using the Service for commercial purposes (e.g., a business entity): The arbitration will be conducted by the AAA under its Commercial Arbitration Rules (available at <span class="blueText">www.adr.org/commercial-rules</span>), or by the ICDR under its International Dispute Resolution Procedures if the dispute involves parties in multiple countries.</li>
            </ul>
            <p class="has-line-data" data-line-start="116" data-line-end="117">The AAA/ICDR will appoint a neutral arbitrator with expertise in technology and internet law (or consumer law, for personal use disputes). If you and we cannot agree on the arbitrator’s qualifications, the AAA/ICDR will select an arbitrator who meets the following criteria: (a) at least 5 years of experience in resolving technology or consumer disputes; (b) no prior relationship with you or us; and © familiarity with the laws of your jurisdiction (if you are a non-U.S. resident).</p>
            <h4 class="code-line" data-line-start=117 data-line-end=118 ><a id="93_Prohibition_of_Class_and_Representative_Actions_and_NonIndividualized_Relief_117"></a>9.3 Prohibition of Class and Representative Actions and Non-Individualized Relief</h4>
            <p class="has-line-data" data-line-start="118" data-line-end="119">YOU AND SINOBIZ LLC AGREE THAT EACH OF US MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, REPRESENTATIVE, OR MASS ACTION OR PROCEEDING (INCLUDING BUT NOT LIMITED TO CLASS ARBITRATIONS, CONSOLIDATED ARBITRATIONS, OR REPRESENTATIVE ACTIONS).</p>
            <p class="has-line-data" data-line-start="120" data-line-end="121">UNLESS BOTH YOU AND SINOBIZ LLC AGREE OTHERWISE IN WRITING, THE ARBITRATOR MAY NOT: (A) CONSOLIDATE OR JOIN MORE THAN ONE PERSON’S OR PARTY’S CLAIMS; (B) PRESIDE OVER ANY FORM OF CLASS, COLLECTIVE, OR REPRESENTATIVE PROCEEDING; OR © AWARD RELIEF THAT BENEFITS ANYONE OTHER THAN THE INDIVIDUAL PARTY SEEKING RELIEF. The arbitrator may award relief (including monetary, injunctive, and declaratory relief) only in favor of the individual party bringing the claim and only to the extent necessary to address that party’s individual claim(s). This provision is non-waivable—any attempt to waive, modify, or void it is invalid unless agreed to in writing by both parties.</p>
            <h4 class="code-line" data-line-start=121 data-line-end=122 ><a id="94_PreArbitration_Dispute_Resolution_121"></a>9.4 Pre-Arbitration Dispute Resolution</h4>
            <p class="has-line-data" data-line-start="122" data-line-end="123">We are committed to resolving disputes amicably and efficiently without arbitration. Before you commence arbitration, you agree to first send a written Notice of Dispute to our legal department at the following address: Sinobiz llc, Attn: Legal Department, 30N GOULD ST STE R SHERIDAN, WY 82801, or via email to <span class="blueText">zhangjian@sinobiz.biz</span> (with the subject line “Notice of Dispute – [Your Full Name/Account ID]”). The Notice must include: (a) your full name, account ID (if applicable), contact information (email/phone), and a description of your relationship with us (e.g., “Melon user since 2025”); (b) a detailed description of the dispute, including the facts giving rise to the claim and the specific legal or contractual basis for the claim; © the specific relief you are seeking (e.g., refund of $50, account reactivation, removal of allegedly infringing content); and (d) any supporting documents (e.g., payment receipts, screenshots, email correspondence).</p>
            <p class="has-line-data" data-line-start="124" data-line-end="125">We will acknowledge receipt of your Notice within 10 business days and will provide a written response (including a proposed resolution, if applicable) within 30 business days of receipt. If we and you cannot resolve the dispute within 60 calendar days of our receipt of the Notice, you or we may commence an arbitration proceeding. If you fail to send a Notice of Dispute before commencing arbitration, the arbitrator will have no authority to proceed, and the arbitration will be dismissed.</p>
            <h4 class="code-line" data-line-start=125 data-line-end=126 ><a id="95_Arbitration_Procedures_125"></a>9.5 Arbitration Procedures</h4>
            <ul>
            <li class="has-line-data" data-line-start="126" data-line-end="127">Location and Format: The arbitration hearing (if any) will be conducted in a location mutually agreed upon by you and us. If no agreement is reached: (a) if you are a U.S. resident, the hearing will be held in the county of your primary residence; (b) if you are a non-U.S. resident, the hearing may be conducted via telephone or video conference (to reduce your travel and cost burden), unless the arbitrator determines an in-person hearing is necessary. All arbitration proceedings (including filings, hearings, and decisions) will be conducted in English, unless you are a non-English speaker and request a translator—we will cover the cost of a professional translator if the arbitrator approves your request.</li>
            <li class="has-line-data" data-line-start="127" data-line-end="128">Fees: Payment of arbitration fees will be governed by the applicable AAA/ICDR Rules, with the following adjustments for individual users (personal, non-commercial use only): (a) If your claim amount is less than $1,000, we will pay all filing fees, arbitrator fees, and administrative costs; (b) If your claim amount is between $1,000 and $10,000, you will pay 20% of the filing fee (up to a maximum of $200), and we will pay the remainder of the filing fee, arbitrator fees, and administrative costs; © If your claim amount exceeds $10,000, fees will be split in accordance with the AAA/ICDR Rules, but we will not require you to pay more than $500 in total fees (we will cover any amount exceeding $500). If we initiate arbitration against you, we will pay all arbitration fees.</li>
            <li class="has-line-data" data-line-start="128" data-line-end="129">Rights in Arbitration: During arbitration, you have the right to: (a) present relevant evidence (e.g., chat logs, payment records, screenshots of Output); (b) cross-examine any witnesses presented by us; © request documents from us (subject to reasonable confidentiality protections); and (d) receive a written explanation of the arbitrator’s decision (including the findings of fact and legal reasoning). The arbitrator will apply the same legal standards that would apply in court and will follow the terms of these Terms.</li>
            <li class="has-line-data" data-line-start="129" data-line-end="130">Decision and Enforcement: The arbitrator’s decision will be final and binding on you and us. Judgment on the award rendered by the arbitrator may be entered in any federal or state court having jurisdiction over the parties. If the arbitrator rules in your favor, we will comply with the award (e.g., issue a refund, reactivate your account) within 15 business days of the award date. If we fail to comply, you may enforce the award through a court of competent jurisdiction.</li>
            </ul>
            <h4 class="code-line" data-line-start=130 data-line-end=131 ><a id="96_Exceptions_to_Arbitration_130"></a>9.6 Exceptions to Arbitration</h4>
            <p class="has-line-data" data-line-start="131" data-line-end="132">Notwithstanding the above, you or we may bring the following claims in court (rather than arbitration): (a) claims for injunctive relief to stop immediate harm (e.g., unauthorized use of your voice in AI covers, ongoing data breaches); (b) small claims court actions (if your claim is within the jurisdiction of your local small claims court and is brought on an individual basis); and © claims arising from patent infringement, trademark infringement, or misappropriation of trade secrets (which may be brought in federal court).</p>
            <h3 class="code-line" data-line-start=133 data-line-end=134 ><a id="10_General_Terms_133"></a>10. General Terms</h3>
            <h4 class="code-line" data-line-start=134 data-line-end=135 ><a id="101_Governing_Law_134"></a>10.1 Governing Law</h4>
            <p class="has-line-data" data-line-start="135" data-line-end="136">These Terms and any action related thereto will be governed by the laws of the State of Delaware, United States, without regard to its conflict of laws provisions. However, if you are a resident of the EEA, UK, Switzerland, or China, the following exceptions apply: (a) For EEA/UK/Switzerland residents: The laws of your country of residence will govern any disputes arising from these Terms (to the extent required by mandatory local law); (b) For China residents: These Terms will be governed by the laws of the People’s Republic of China (excluding Hong Kong, Macau, and Taiwan), except for provisions that conflict with mandatory Chinese law (which will prevail).</p>
            <h4 class="code-line" data-line-start=136 data-line-end=137 ><a id="102_Venue_136"></a>10.2 Venue</h4>
            <p class="has-line-data" data-line-start="137" data-line-end="138">Subject to the Arbitration Agreement in Section 9, the exclusive jurisdiction for all disputes that you and Sinobiz llc are not required to arbitrate will be: (a) If you are a U.S. resident: The state and federal courts located in New Castle County, Delaware; (b) If you are a China resident: The people’s court of the district where our registered office in China is located (or the court with jurisdiction over your place of residence, if more convenient); © If you are a resident of any other country: The courts of</p>
            <p class="has-line-data" data-line-start="139" data-line-end="140">your country of residence that have jurisdiction over disputes involving foreign entities (provided such courts are competent to hear the matter). You and Sinobiz llc each waive any objection to jurisdiction and venue in such courts, including objections based on “forum non conveniens” or lack of personal jurisdiction.</p>
            <h4 class="code-line" data-line-start=140 data-line-end=141 ><a id="103_Severability_No_Waiver_and_Assignment_140"></a>10.3 Severability, No Waiver, and Assignment</h4>
            <ul>
            <li class="has-line-data" data-line-start="141" data-line-end="142">Severability: If any provision of these Terms is held to be invalid, illegal, or unenforceable by a court or arbitrator of competent jurisdiction, that provision will be struck from these Terms, but the remaining provisions will remain in full force and effect. The invalidity of a provision will not affect the validity of any other provision, and we will interpret the remaining provisions to reflect the original intent of these Terms as closely as possible. For example, if a court finds the class action waiver in Section 9.3 unenforceable, all other provisions of the Arbitration Agreement (e.g., requirement for individual arbitration) will still apply.</li>
            <li class="has-line-data" data-line-start="142" data-line-end="143">No Waiver: Our failure to enforce any right or provision of these Terms at any time will not be deemed a waiver of that right or provision, nor will it prevent us from enforcing that right or provision in the future. A waiver of any breach of these Terms will not constitute a waiver of any subsequent breach.</li>
            <li class="has-line-data" data-line-start="143" data-line-end="144">Assignment: You may not assign or transfer these Terms, or any of your rights or obligations under them, by operation of law (e.g., bankruptcy, divorce) or otherwise, without our prior written consent. Any attempted assignment or transfer without such consent will be null and void. We may freely assign or transfer these Terms, or any of our rights or obligations under them, to any third party (e.g., a subsidiary, affiliate, or successor entity in a merger or acquisition) without your consent. Such assignment will not affect your rights or our obligations under these Terms.</li>
            </ul>
            <h4 class="code-line" data-line-start=144 data-line-end=145 ><a id="104_Interpretation_of_Terms_144"></a>10.4 Interpretation of Terms</h4>
            <p class="has-line-data" data-line-start="145" data-line-end="146">In the event of any ambiguity or dispute regarding the interpretation of these Terms, the following rules will apply: (a) Words in the singular form include the plural and vice versa (e.g., “user” includes “users,” “Credit” includes “Credits”); (b) References to “including,” “such as,” or “for example” are illustrative and not exhaustive—they do not limit the scope of the preceding term; © Provisions that are invalid or unenforceable will be interpreted to give effect to their original intent (to the extent legally possible) without affecting the validity of other provisions; (d) Headings and subheadings are for organizational convenience only and do not affect the interpretation of the corresponding provisions; (e) For users outside the U.S., any conflict between these Terms and the mandatory laws of your jurisdiction (e.g., consumer protection laws, data privacy laws) will be resolved in favor of such mandatory laws; (f) References to “days” mean calendar days, unless explicitly stated as “business days” (which exclude weekends and U.S. federal holidays, or the official holidays of your jurisdiction if you are a non-U.S. user).</p>
            <h4 class="code-line" data-line-start=146 data-line-end=147 ><a id="105_Force_Majeure_146"></a>10.5 Force Majeure</h4>
            <p class="has-line-data" data-line-start="147" data-line-end="148">We will not be liable for any failure or delay in performing our obligations under these Terms if such failure or delay is caused by circumstances beyond our reasonable control, including but not limited to: natural disasters (e.g., earthquakes, floods, hurricanes); acts of war, terrorism, or civil unrest; government actions (e.g., bans, sanctions, shutdowns); internet outages, server failures, or other technical issues not caused by our negligence; or shortages of materials or labor that affect our service providers. In such cases, we will notify you of the delay as soon as reasonably possible and will use reasonable efforts to resume performance once the cause of the delay is resolved. The time for us to perform our obligations will be extended by the duration of the delay.</p>
            <h4 class="code-line" data-line-start=148 data-line-end=149 ><a id="106_Entire_Agreement_148"></a>10.6 Entire Agreement</h4>
            <p class="has-line-data" data-line-start="149" data-line-end="150">These Terms, together with our Melon Privacy Policy and any additional terms you agree to (e.g., terms for promotional offers, third-party service integrations), constitute the entire agreement between you and Sinobiz llc regarding your use of the Service. They supersede all prior or contemporaneous agreements, understandings, and representations (whether oral or written) between you and us relating to the Service. If there is a conflict between these Terms and the Privacy Policy, the Privacy Policy will prevail with respect to matters related to the collection, use, and protection of your personal information; for all other matters, these Terms will prevail.</p>
            <h4 class="code-line" data-line-start=150 data-line-end=151 ><a id="107_Contact_Information_150"></a>10.7 Contact Information</h4>
            <p class="has-line-data" data-line-start="151" data-line-end="152">If you have any questions, concerns, or feedback about these Terms or the Service, please contact us at:</p>
            <p class="has-line-data" data-line-start="153" data-line-end="155">Sinobiz llc<br>
            30N GOULD ST STE R SHERIDAN, WY 82801</p>
            <p class="has-line-data" data-line-start="156" data-line-end="158">Email: <span class="blueText">zhangjian@sinobiz.biz</span><br>
            Response Time: We will use reasonable efforts to respond to your inquiry within 5 business days. For urgent matters (e.g., account suspension, unauthorized activity), we will aim to respond within 24 hours.</p>
        </body>
    </html>
`

export default HTML